version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
 
  kafka:
    build: ../kafka
    ports:
      - "9092:9092"
      - "8082:8082"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "ansotopic1:1:1,ansotopic8:1:1,ansotopic100:1:1,ansotopic101:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
#    volumes:
#      - /c/Users/asochal/volumes/kafka:/kafka


  vertx:    
    build:
      context: ./vertx
    ports:      
      - "10080:10080" 
    depends_on:
      - kafka
    volumes:
      - /c/Users/asochal/volumes/vertx:/vertx/webroot

  vertx2:    
    build:
      context: ./vertx2
    ports:      
      - "10081:10081" 
    depends_on:
      - kafka
    volumes:
      - /c/Users/asochal/volumes/vertx2:/vertx/webroot

  spark:
    build:
      context: ./spark-nb
      args:
        - GRANT_SUDO=yes
        - NOTEBOOK_DIR=/home/jovyan/work
    ports:      
      - "8888:8888"
    environment:
      - GRANT_SUDO=yes
      #- SPARK_OPTS=--master=local --repositories http://repository.mapr.com/maven --packages org.apache.hbase:hbase-client:1.1.1-mapr-1602-m7-5.1.0,org.apache.hbase:hbase-server:1.1.1-mapr-1602-m7-5.1.0
    volumes:
      - /c/Users/asochal/volumes/spark_sci/notebook:/home/jovyan/notebook
      - /c/Users/asochal/volumes/spark_sci/data:/home/jovyan/data
    entrypoint: start-notebook.sh --NotebookApp.token=''
    depends_on:
      - kafka
      - zookeeper
      - vertx
