version: '2'
services:

  mongo:
    build: ../mongo
    ports:
      - "27017:27017"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- /c/Users/asochal/volumes/mongo/data:/data/db
      #- /c/Users/asochal/volumes/mongo/config:/data/configdb
    
  mongoclient:    
    build:
      context: ./mongoclient
    ports:      
      - "3000:3000" 
    depends_on:
      - mongo
