# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM jupyter/pyspark-notebook

MAINTAINER Jupyter Project <jupyter@googlegroups.com>

USER root

# RSpark config
ENV R_LIBS_USER $SPARK_HOME/R/lib

# R pre-requisites
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    fonts-dejavu \
    gfortran \
    gcc && apt-get clean && \
    rm -rf /var/lib/apt/lists/*


RUN apt-get update \
	&& apt-get upgrade -y \
	&& apt-get install -y unzip wget build-essential \
		cmake git pkg-config libswscale-dev \
		python3-dev python3-numpy \
		libtbb2 libtbb-dev libjpeg-dev \
		libpng-dev libtiff-dev libjasper-dev


RUN pip install --upgrade pip
RUN pip install -U setuptools --ignore-installed

RUN echo $NB_USER
USER $NB_USER
# R packages
# Pin r-base to a specific build number for https://github.com/jupyter/docker-stacks/issues/210#issuecomment-246081809
RUN conda config --add channels r && \
    conda install --quiet --yes \
    'r-base=3.3.1 1' \
    'r-irkernel=0.7*' \
    'r-ggplot2=2.1*' \
    'r-rcurl=1.95*' && conda clean -tipsy

USER root

RUN cd \
	&& wget https://github.com/opencv/opencv/archive/3.1.0.zip \
	&& unzip 3.1.0.zip \
	&& cd opencv-3.1.0 \
	&& mkdir build \
	&& cd build \
	&& cmake \
	-D PYTHON_EXECUTABLE=/opt/conda/bin/python \
    -D PYTHON_LIBRARY=/opt/conda/lib/libpython3.5m.so \
    -D PYTHON_INCLUDE_DIR=/opt/conda/include/python3.5m \
	-D PYTHON_NUMPY_INCLUDE_DIRS=/opt/conda/lib/python3.5/site-packages/numpy/core/include/numpy \
    -D PYTHON_PACKAGES_PATH=/opt/conda/lib/python3.5/site-packages \
    -D BUILD_opencv_legacy=OFF .. \
	&& make -j3 \
	&& make install \
	&& cd \
	&& rm 3.1.0.zip	
	
	
#-D PYTHON_NUMPY_INCLUDE_DIRS=/opt/conda/lib/python3.5/site-packages/numpy/core/include/numpy \
	
# Apache Toree kernel

USER $NB_USER
RUN pip --no-cache-dir install toree==0.1.0.dev7
RUN jupyter toree install --user
RUN pip install h2o

RUN pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0-cp35-cp35m-linux_x86_64.whl 

USER root

