version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  hbase:
    build: .
    ports:      
      - "16010:16010" 
      - "9095:9095"
      - "8085:8085"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /c/Users/asochal/volumes/hbase:/data
